-- Supabase SQL setup for CETI Maria Neusa de Sousa
-- Run this script in the Supabase SQL Editor.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Admins
CREATE TABLE IF NOT EXISTS admins (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- 2. Students
CREATE TABLE IF NOT EXISTS students (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  classname TEXT NOT NULL,
  user TEXT UNIQUE,
  password TEXT,
  must_change_password BOOLEAN NOT NULL DEFAULT false,
  is_journalist BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- 3. Teachers
CREATE TABLE IF NOT EXISTS teachers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  classes TEXT[] DEFAULT '{}',
  user TEXT UNIQUE,
  password TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- 4. Classes
CREATE TABLE IF NOT EXISTS classes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);

-- 5. Subjects
CREATE TABLE IF NOT EXISTS subjects (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);

-- Vinculos exatos: cada linha representa uma disciplina lecionada em uma turma.
CREATE TABLE IF NOT EXISTS teacher_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id TEXT NOT NULL,
  subject TEXT NOT NULL,
  classname TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (teacher_id, subject, classname)
);

-- 6. Grades
CREATE TABLE IF NOT EXISTS grades (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  studentId UUID REFERENCES students(id) ON DELETE CASCADE,
  subject TEXT NOT NULL,
  classname TEXT NOT NULL,
  trimesters JSONB DEFAULT '{"1":{"n1":0,"n2":0,"n3":0,"recovery":false},"2":{"n1":0,"n2":0,"n3":0,"recovery":false},"3":{"n1":0,"n2":0,"n3":0,"recovery":false}}',
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- 7. News
CREATE TABLE IF NOT EXISTS news (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  summary TEXT,
  content TEXT,
  category TEXT,
  author TEXT,
  date TEXT,
  published BOOLEAN DEFAULT false,
  files JSONB DEFAULT '[]',
  created_by_student_id TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- 8. Events
CREATE TABLE IF NOT EXISTS events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  date TEXT NOT NULL,
  time TEXT,
  location TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- 9. Activities
CREATE TABLE IF NOT EXISTS activities (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  files JSONB DEFAULT '[]',
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- 10. Achievements
CREATE TABLE IF NOT EXISTS achievements (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  files JSONB DEFAULT '[]',
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- Garante as colunas de anexos em bancos criados por versoes anteriores.
ALTER TABLE news ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS author TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT false;
ALTER TABLE news ADD COLUMN IF NOT EXISTS files JSONB DEFAULT '[]'::jsonb;
ALTER TABLE news ADD COLUMN IF NOT EXISTS created_by_student_id TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS is_journalist BOOLEAN DEFAULT false;
ALTER TABLE students ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE activities ADD COLUMN IF NOT EXISTS files JSONB DEFAULT '[]'::jsonb;
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS files JSONB DEFAULT '[]'::jsonb;

-- 11. School configuration
CREATE TABLE IF NOT EXISTS school_config (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  history TEXT DEFAULT '',
  mission TEXT DEFAULT '',
  vision TEXT DEFAULT '',
  "values" TEXT DEFAULT '',
  address TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  email TEXT DEFAULT '',
  team JSONB DEFAULT '[]',
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);

-- 12. Seed admin account
INSERT INTO admins (user, password)
VALUES ('admin', 'cetimns26')
ON CONFLICT (user) DO UPDATE SET
  password = EXCLUDED.password;

-- 13. Seed school configuration
INSERT INTO school_config (id, history, mission, vision, "values", address, phone, email, team)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'CETI Maria Neusa de Sousa - Centro Estadual de Tempo Integral',
  'Formar cidadaos criticos e competentes',
  'Excelencia em educacao integral',
  'Respeito, Responsabilidade, Inovacao',
  'Francisco Macedo, PI',
  '(86) XXXX-XXXX',
  'ceti@seduc.pi.gov.br',
  '[]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  history = EXCLUDED.history,
  mission = EXCLUDED.mission,
  vision = EXCLUDED.vision,
  "values" = EXCLUDED."values",
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  team = EXCLUDED.team;

-- 14. Permissoes para o frontend via anon key
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE school_config ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'teacher_assignments' AND policyname = 'teacher_assignments_full_access'
  ) THEN
    CREATE POLICY teacher_assignments_full_access ON teacher_assignments FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'admins' AND policyname = 'admins_full_access'
  ) THEN
    CREATE POLICY admins_full_access ON admins FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'students' AND policyname = 'students_full_access'
  ) THEN
    CREATE POLICY students_full_access ON students FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'teachers' AND policyname = 'teachers_full_access'
  ) THEN
    CREATE POLICY teachers_full_access ON teachers FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'classes' AND policyname = 'classes_full_access'
  ) THEN
    CREATE POLICY classes_full_access ON classes FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'subjects' AND policyname = 'subjects_full_access'
  ) THEN
    CREATE POLICY subjects_full_access ON subjects FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'grades' AND policyname = 'grades_full_access'
  ) THEN
    CREATE POLICY grades_full_access ON grades FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'news' AND policyname = 'news_full_access'
  ) THEN
    CREATE POLICY news_full_access ON news FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'events' AND policyname = 'events_full_access'
  ) THEN
    CREATE POLICY events_full_access ON events FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'activities' AND policyname = 'activities_full_access'
  ) THEN
    CREATE POLICY activities_full_access ON activities FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'achievements' AND policyname = 'achievements_full_access'
  ) THEN
    CREATE POLICY achievements_full_access ON achievements FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'school_config' AND policyname = 'school_config_full_access'
  ) THEN
    CREATE POLICY school_config_full_access ON school_config FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;
END $$;
