-- Execute uma vez no SQL Editor do Supabase para atualizar um banco existente.
-- Alem dos anexos, garante todos os campos usados pelo painel atual.
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS author TEXT;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS published BOOLEAN DEFAULT false;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS files JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS created_by_student_id TEXT;

ALTER TABLE public.students ADD COLUMN IF NOT EXISTS is_journalist BOOLEAN DEFAULT false;

-- Configuracoes institucionais: garante compatibilidade com bancos criados em versoes anteriores.
ALTER TABLE public.school_config ADD COLUMN IF NOT EXISTS history TEXT DEFAULT '';
ALTER TABLE public.school_config ADD COLUMN IF NOT EXISTS mission TEXT DEFAULT '';
ALTER TABLE public.school_config ADD COLUMN IF NOT EXISTS vision TEXT DEFAULT '';
ALTER TABLE public.school_config ADD COLUMN IF NOT EXISTS "values" TEXT DEFAULT '';
ALTER TABLE public.school_config ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '';
ALTER TABLE public.school_config ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '';
ALTER TABLE public.school_config ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '';
ALTER TABLE public.school_config ADD COLUMN IF NOT EXISTS team JSONB DEFAULT '[]'::jsonb;

-- O upsert do painel usa `onConflict: 'id'`; bancos muito antigos podem ter
-- a coluna sem uma restricao unica. Garante a chave necessaria para o upsert.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.school_config'::regclass
      AND contype IN ('p', 'u')
      AND conkey = ARRAY[
        (SELECT attnum FROM pg_attribute
         WHERE attrelid = 'public.school_config'::regclass
           AND attname = 'id' AND NOT attisdropped)
      ]
  ) THEN
    ALTER TABLE public.school_config ADD CONSTRAINT school_config_pkey PRIMARY KEY (id);
  END IF;
END $$;

ALTER TABLE public.school_config ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.school_config TO anon, authenticated;

DROP POLICY IF EXISTS school_config_full_access ON public.school_config;
CREATE POLICY school_config_full_access ON public.school_config
  FOR ALL TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- Atualiza bancos antigos, nos quais eventos usavam apenas event_date.
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS time TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS files JSONB DEFAULT '[]'::jsonb;
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'events' AND column_name = 'event_date'
  ) THEN
    EXECUTE 'UPDATE public.events SET date = event_date::text WHERE date IS NULL AND event_date IS NOT NULL';
  END IF;
END $$;

ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS files JSONB DEFAULT '[]'::jsonb;

ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.achievements ADD COLUMN IF NOT EXISTS files JSONB DEFAULT '[]'::jsonb;

NOTIFY pgrst, 'reload schema';

-- Vinculos exatos entre professor, disciplina e turma.
CREATE TABLE IF NOT EXISTS public.teacher_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id TEXT NOT NULL,
      subject TEXT NOT NULL,
        classname TEXT NOT NULL,
          created_at TIMESTAMPTZ DEFAULT now(),
            UNIQUE (teacher_id, subject, classname)
            );

            CREATE INDEX IF NOT EXISTS teacher_assignments_teacher_id_idx
              ON public.teacher_assignments (teacher_id);

              -- Permite ao portal atual gerenciar o conteudo usando a chave publica.
              ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
              ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
              ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
              ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
              ALTER TABLE public.teacher_assignments ENABLE ROW LEVEL SECURITY;

              GRANT SELECT, INSERT, UPDATE, DELETE ON public.news TO anon, authenticated;
              GRANT SELECT, INSERT, UPDATE, DELETE ON public.activities TO anon, authenticated;
              GRANT SELECT, INSERT, UPDATE, DELETE ON public.achievements TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.events TO anon, authenticated;
              GRANT SELECT, INSERT, UPDATE, DELETE ON public.teacher_assignments TO anon, authenticated;
              GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

              DROP POLICY IF EXISTS portal_news_full_access ON public.news;
              CREATE POLICY portal_news_full_access ON public.news
                FOR ALL TO anon, authenticated
                  USING (true)
                    WITH CHECK (true);

                    DROP POLICY IF EXISTS portal_activities_full_access ON public.activities;
                    CREATE POLICY portal_activities_full_access ON public.activities
                      FOR ALL TO anon, authenticated
                        USING (true)
                          WITH CHECK (true);

                          DROP POLICY IF EXISTS portal_achievements_full_access ON public.achievements;
                          CREATE POLICY portal_achievements_full_access ON public.achievements
                            FOR ALL TO anon, authenticated
                              USING (true)
                              WITH CHECK (true);

                                DROP POLICY IF EXISTS portal_events_full_access ON public.events;
                                CREATE POLICY portal_events_full_access ON public.events
                                  FOR ALL TO anon, authenticated
                                    USING (true)
                                      WITH CHECK (true);

                                DROP POLICY IF EXISTS portal_teacher_assignments_full_access ON public.teacher_assignments;
                                CREATE POLICY portal_teacher_assignments_full_access ON public.teacher_assignments
                                  FOR ALL TO anon, authenticated
                                    USING (true)
                                      WITH CHECK (true);

                                      NOTIFY pgrst, 'reload schema';
                                      
